version: '3.1'

networks:
  redmine:
    external: false

services:

  redmine:
    container_name: redmine
    image: redmine:5
    restart: unless-stopped
    networks:
      - redmine
    hostname: redmine
    expose:
      - 3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: redmine
      REDMINE_SECRET_KEY_BASE: redmine
      REDMINE_PLUGINS_MIGRATE: true
      TZ: Europe/Moscow
    volumes:
      - ./data/redmine/files:/usr/src/redmine/files
      - ./data/redmine/plugins:/usr/src/redmine/plugins
      - ./data/redmine/themes:/usr/src/redmine/public/themes

  db:
    container_name: redmine_db
    image: mariadb:10.6
    restart: unless-stopped
    networks:
      - redmine
    environment:
      MARIADB_ROOT_PASSWORD: redmine
      MARIADB_DATABASE: redmine
      TZ: Europe/Moscow
    volumes:
     - ./data/redmine/db:/var/lib/mysql

  nginx:
    image: nginx:1
    container_name: nginx
    environment:
      TZ: Europe/Moscow
    volumes:
      - ./logs/nginx/:/var/log/nginx/
      - type: bind
        source: ./nginx/config/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    hostname: nginx
    networks:
      - redmine
    ports:
      - 80:80
      - 443:443
    links:
      - redmine
    depends_on:
      - redmine
    command: ["nginx", "-g", "daemon off;"]
    restart: unless-stopped